"""Initial tables

Revision ID: 2f527c09c13f
Revises: 
Create Date: 2021-11-02 22:30:55.889966

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f527c09c13f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_information',
    sa.Column('m_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('links', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('resume', postgresql.BYTEA(), nullable=True),
    sa.Column('picture', postgresql.BYTEA(), nullable=True),
    sa.PrimaryKeyConstraint('m_id')
    )
    op.create_table('organization',
    sa.Column('o_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('o_id')
    )
    op.create_table('org_member_association',
    sa.Column('member_info_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['member_info_id'], ['member_information.m_id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.o_id'], ),
    sa.PrimaryKeyConstraint('member_info_id', 'organization_id')
    )
    op.create_table('organization_highlight',
    sa.Column('oh_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('attachment', postgresql.BYTEA(), nullable=True),
    sa.Column('o_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['o_id'], ['organization.o_id'], ),
    sa.PrimaryKeyConstraint('oh_id')
    )
    op.create_table('user',
    sa.Column('u_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('m_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['m_id'], ['member_information.m_id'], ),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('org_administrator_association',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.o_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'organization_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_administrator_association')
    op.drop_table('user')
    op.drop_table('organization_highlight')
    op.drop_table('org_member_association')
    op.drop_table('organization')
    op.drop_table('member_information')
    # ### end Alembic commands ###
