"""Added image row to user and organization

Revision ID: d22bbc824024
Revises: b423ed47d1b8
Create Date: 2021-11-26 16:24:57.840042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd22bbc824024'
down_revision = 'b423ed47d1b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('i_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'organization', 'image', ['i_id'], ['i_id'])
    op.add_column('user', sa.Column('i_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'user', 'image', ['i_id'], ['i_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'i_id')
    op.drop_constraint(None, 'organization', type_='foreignkey')
    op.drop_column('organization', 'i_id')
    # ### end Alembic commands ###
