"""testing

Revision ID: eeb2bf73d869
Revises: 
Create Date: 2021-10-30 22:23:59.985551

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eeb2bf73d869'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('organization_highlight')
    op.drop_table('organization')
    op.drop_table('org_member_association')
    op.drop_table('org_administrator_association')
    op.drop_table('member_information')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_information',
    sa.Column('m_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('links', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('resume', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('picture', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('m_id', name='member_information_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('org_administrator_association',
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.o_id'], name='org_administrator_association_organization_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.u_id'], name='org_administrator_association_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'organization_id', name='org_administrator_association_pkey')
    )
    op.create_table('org_member_association',
    sa.Column('member_info_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_info_id'], ['member_information.m_id'], name='org_member_association_member_info_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.o_id'], name='org_member_association_organization_id_fkey'),
    sa.PrimaryKeyConstraint('member_info_id', 'organization_id', name='org_member_association_pkey')
    )
    op.create_table('organization',
    sa.Column('o_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('o_id', name='organization_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('organization_highlight',
    sa.Column('oh_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attachment', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('o_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['o_id'], ['organization.o_id'], name='organization_highlight_o_id_fkey'),
    sa.PrimaryKeyConstraint('oh_id', name='organization_highlight_pkey')
    )
    op.create_table('user',
    sa.Column('u_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('u_id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    # ### end Alembic commands ###
